apiVersion: v1
kind: ConfigMap
metadata:
  name: micro-service-router
  namespace: spring-kubernetes-cloud
data:
  application.yaml: |-
    server:
      port: ${SERVER_PORT:8000}
      tomcat:
        remoteip:
          host-header: X-Real-IP
        max-http-form-post-size: 30MB
        connection-timeout: 120000
      netty:
        connection-timeout: 120000
    spring:
      config:
        activate:
          on-profile: production
      cloud:
        gateway:
          httpclient:
            pool:
              max-idle-time: 10000
          routes:
            - id: pass-saas-certification
              uri: lb://pass-saas-certification
              predicates:
                - Path=/certification/**
              filters:
                - StripPrefix=1
    ---
    server:
      port: ${SERVER_PORT:8000}
      tomcat:
        remoteip:
          host-header: X-Real-IP
        max-http-form-post-size: 30MB
        connection-timeout: 120000
      netty:
        connection-timeout: 120000
    spring:
      config:
        activate:
          on-profile: production
      cloud:
        gateway:
          httpclient:
            pool:
              max-idle-time: 10000
          routes:
            - id: pass-saas-certification
              uri: lb://pass-saas-certification
              predicates:
                - Path=/certification/**
              filters:
                - StripPrefix=1
    ---
    server:
      port: ${SERVER_PORT:8000}
      tomcat:
        remoteip:
          host-header: X-Real-IP
        max-http-form-post-size: 30MB
        connection-timeout: 120000
      netty:
        connection-timeout: 120000
    spring:
      config:
        activate:
          on-profile: production
      cloud:
        gateway:
          httpclient:
            pool:
              max-idle-time: 10000
          routes:
            - id: pass-saas-certification
              uri: lb://pass-saas-certification
              predicates:
                - Path=/certification/**
              filters:
                - StripPrefix=1