apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: spring-kubernetes-cloud
  name: cloud-service-k8s-service-role
rules:
  - apiGroups: [ "", "extensions", "apps" ]
    resources: [ "configmaps", "pods", "services", "endpoints", "secrets" ]
    verbs: [ "get", "list", "watch" ]