apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: kubernetes-cloud-service-k8s-role-binding
  name: kubernetes-cloud-service-k8s-role-binding:view
  namespace: spring-kubernetes-cloud
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: cloud-service-k8s-service-role
subjects:
  - kind: ServiceAccount
    name: cloud-service-k8s-service-account