spring:
  shardingsphere:
    props:
      sql-show: true
    rules:
      sharding:
        sharding-algorithms:
          database-inline:
            type: INLINE
            props:
              algorithm-expression: cloud_native_node_${Math.abs(cid.hashCode()) % 3}
        tables:
          sys_user:
            actual-data-nodes: cloud_native_node_${0..2}.sys_user
            #            table-strategy:
            #              standard:
            #                sharding-column: cid
            #                sharding-algorithm-name: database-inline
            database-strategy:
              standard:
                sharding-column: cid
                sharding-algorithm-name: database-inline
          sys_user_identity:
            actual-data-nodes: cloud_native_node_${0..2}.sys_user_identity
            database-strategy:
              standard:
                sharding-column: user_cid  # 分片键，用于分片的字段名
                sharding-algorithm-name: database-inline  # 使用的分片算法的名称
#        default-database-strategy:
#          standard:
#            sharding-column: cid  # 分片键，用于分片的字段名
#            sharding-algorithm-name: database-inline  # 使用的分片算法的名称