spring:
  cloud:
    kubernetes:
      discovery:
        namespaces:
          - spring-kubernetes-cloud
      config:
        namespace: spring-kubernetes-cloud
        enabled: true
        name: sso-service-config